### ISSUE TITLE
Magento 2.4.3 Compatibility: \Zend\Log\Writer\Stream Class Not Exists

### ISSUE THREAD

**Issue by sanchit-redmonks** [paytabscom/paytabs-magento2.x#21]
In Magento 2.4.3 the \Zend\Log\Writer\Stream and \Zend\Log\Logger are not exist. These classes are being used in the PayTabs\PayPage\Gateway\Http\PaytabsCore.php file. 

So kindly update the module accordingly.

Thank you

**Comment by wajihkm** [comment]
Hi @sanchit-redmonks 
Thanks for the note, we will check it.

Regards,

**Comment by wajihkm** [comment]
Fixed in version 3.5.3
