### ISSUE TITLE
stop sending e-mail for the customer when the payment is not completed or canceled

### ISSUE THREAD

**Issue by khaledsawwaf** [paytabscom/paytabs-magento2.x#4]
I'm using payment with PayTabs credit card.
When the customer finishes the Order, clicking on "Pay the order" to be redirected to PayTabs server and then clicked on Cancel, the Magento 2 system sends an e-mail for the customer like he did finish the order successfully! while he is not, and he sould not receive any e-mail if he didn't enter the correct credit card details and proceed with the payment.

**Comment by wajihkm** [comment]
Hi @khaledsawwaf ,

Kindly accept our apology about this case.
We will check it and come back soon.

Thanks

**Comment by arshadmuhammad** [comment]
@wajihkm is there any update regarding this error, I also face this issue.

**Comment by wajihkm** [comment]
Hi @khaledsawwaf , @arshadmuhammad  

Kindly try our latest release [2.4.0 (PT2)](https://github.com/paytabscom/paytabs-magento2.x/tree/PT2)
We have added options to Admin panel to control the Email confirmation
