### ISSUE TITLE
Order set as processing and send email after create order.

### ISSUE THREAD

**Issue by arshadmuhammad** [paytabscom/paytabs-magento2.x#5]
When I create an order with paytabs order is created with the status processing and sends an email to the customer without paying any payment via paytabs. I look into the extension but I didn't figure out where this issue is occurred kindly fix this bug asap.

**Comment by wajihkm** [comment]
Hi @arshadmuhammad 

Kindly try our latest release [2.4.0 (PT2)](https://github.com/paytabscom/paytabs-magento2.x/tree/PT2)
We have added options to Admin panel to control the Email confirmation
