### ISSUE TITLE
Compatibility Inquiry: Is this module compatible with Magento 2.4.7?

### ISSUE THREAD

**Issue by fathimazubairpgp** [paytabscom/paytabs-magento2.x#81]
Hi @wajihkm @arsalanworld @Walaa-Elsaeed-93 ,

First of all, thank you for developing and maintaining this module. It has been incredibly helpful for our Magento store operations.

I am currently using this module with Magento 2.4.2-p2, and it has been working seamlessly. As we are planning to upgrade our store to Magento 2.4.7, I wanted to inquire if this module is compatible with Magento 2.4.7.

Your guidance on this would be greatly appreciated. Please let me know if there are any updates or steps required to ensure smooth compatibility.

Thank you for your support, and I look forward to your response!

Best regards,
Fathima Zubair

**Comment by wajihkm** [comment]
Hi @fathimazubairpgp 

Glad to hear that the module works fine with you.
Yes, it is compatible with latest Magento release 2.4.7 (tested on 2.4.7 p2)

However, if you would like to test it, you can use our docker image to setup a new store with any Magento version you like, and the module (plugin) will be auto installed as well.

https://github.com/paytabscom/docker-magento2
Note: the docker repo uses a submodule:
(https://github.com/paytabscom/docker-common-plugins)

You will find the installation instructions in ReadMe file.

Thanks
Wajih
